apiVersion: app.claw.cloud/v1
kind: Template
metadata:
  name: nezha
spec:
  title: 'Nezha Monitoring Dashboard'
  type: official
  author: ClawCloud Run
  author_id: 180503656
  date: 2025-06-19
  url: 'https://github.com/nezhahq/nezha'
  gitRepo: 'https://github.com/nezhahq/nezha'
  description: 'A lightweight, self-hosted monitoring dashboard with client probes.'
  readme: 'https://raw.githubusercontent.com/ClawCloud/Run-Template/refs/heads/main/template/nezha/README.md'
  icon: 'https://avatars.githubusercontent.com/u/105093572?s=48&v=4'
  templateType: inline
  locale: en
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: nezha-${{ random(6) }}
  inputs:

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/nezhahq/nezha:v1.13.0
    deploy.run.claw.cloud/minReplicas: '1'
    deploy.run.claw.cloud/maxReplicas: '1'
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  serviceName: ${{ defaults.app_name }}
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/nezhahq/nezha:v1.13.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 51Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8008
            - containerPort: 5555
          volumeMounts:
            - name: dashboard-data
              mountPath: /opt/nezha/dashboard/data
            - name: static-custom
              mountPath: /opt/nezha/dashboard/resource/static/custom/
            - name: theme-custom
              mountPath: /opt/nezha/dashboard/resource/template/theme-custom/
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /opt/nezha/dashboard/data
          value: '1'
        name: dashboard-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /opt/nezha/dashboard/resource/static/custom/
          value: '1'
        name: static-custom
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
    - metadata:
        annotations:
          path: /opt/nezha/dashboard/resource/template/theme-custom/
          value: '1'
        name: theme-custom
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi


---

apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - name: http
      port: 8008
      targetPort: 8008
    - name: grpc
      port: 5555
      targetPort: 5555
  selector:
    app: ${{ defaults.app_name }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-combined
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
  annotations:
    kubernetes.io/ingress.class: nginx

    # UI traffic annotations
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/server-snippet: |
      # Cache static assets
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      secretName: ${{ CLAWCLOUD_CERT_SECRET_NAME }}
  rules:
    - host: ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      http:
        paths:
          - path: /proto.NezhaService
            pathType: Prefix
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 5555
            nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8008
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
