apiVersion: app.claw.cloud/v1
kind: Template
metadata:
  name: nezha
spec:
  title: 'Nezha Monitoring Dashboard'
  type: official
  author: ClawCloud Run
  author_id: 180503656
  date: 2025-06-19
  url: 'https://github.com/nezhahq/nezha'
  gitRepo: 'https://github.com/nezhahq/nezha'
  description: 'A lightweight, self-hosted monitoring dashboard with client probes.'
  readme: 'https://raw.githubusercontent.com/ClawCloud/Run-Template/refs/heads/main/template/nezha/README.md' 
  icon: 'https://avatars.githubusercontent.com/u/105093572?s=48&v=4'
  templateType: inline
  locale: en
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: ${{ random(12) }}
    app_name:
      type: string
      value: nezha-${{ random(6) }}
  inputs:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: lsposed/nezha
    deploy.run.claw.cloud/minReplicas: '1'
    deploy.run.claw.cloud/maxReplicas: '1'
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: lsposed/nezha
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          command:
            - sh
            - -c
            - |
              chmod +x /opt/nezha/dashboard/dashboard-linux-amd64
              exec /opt/nezha/dashboard/dashboard-linux-amd64 
          args: []
          ports:
            - containerPort: 8008
          volumeMounts:
            - name: vn-optvn-nezhavn-dashboardvn-data
              mountPath: /opt/nezha/dashboard/data
            - name: vn-staticvn-custom
              mountPath: /opt/nezha/dashboard/resource/static/custom/
            - name: vn-themevn-custom
              mountPath: /opt/nezha/dashboard/resource/template/theme-custom/
      volumes:
        - name: vn-optvn-nezhavn-dashboardvn-data
          emptyDir: {}
        - name: vn-staticvn-custom
          emptyDir: {}
        - name: vn-themevn-custom
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8008
  selector:
    app: ${{ defaults.app_name }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    run.claw.cloud/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8008
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      secretName: ${{ CLAWCLOUD_CERT_SECRET_NAME }}
