apiVersion: app.claw.cloud/v1
kind: Template
metadata:
  name: btpanel
spec:
  title: 'BaoTa Panel'
  url: 'https://www.bt.cn/'
  gitRepo: 'https://cnb.cool/btpanel/BaoTa'
  author: 'BTPanel'
  description: 'Baota Panel is a secure and efficient server management panel that enables one-click configuration of LAMP/LNMP stacks, websites, databases, FTP, and SSL'
  readme: 'https://raw.githubusercontent.com/ClawCloud/Run-Template/refs/heads/main/template/btpanel/README.md'
  icon: 'https://www.bt.cn/static/new/images/logo_03.svg'
  templateType: inline
  locale: en
  categories:
    - dev-ops
  defaults:
    app_name:
      type: string
      value: btpanel-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:

---

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: docker.cnb.cool/btpanel/btpanel
    deploy.run.claw.cloud/minReplicas: '1'
    deploy.run.claw.cloud/maxReplicas: '1'
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
      - name: ${{ defaults.app_name }}
        image: docker.cnb.cool/btpanel/btpanel:nas
        ports:
        - containerPort: 8888
        - containerPort: 80
        - containerPort: 443
        - containerPort: 3306
        - containerPort: 22
        - containerPort: 21
        volumeMounts:
        - name: vn-wwwvn-wwwroot
          mountPath: /www/wwwroot
        - name: vn-wwwvn-servervn-data
          mountPath: /www/server/data
        resources:
          requests:
            cpu: 200m
            memory: 204Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /www/wwwroot
          value: '1'
        name: vn-wwwvn-wwwroot
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /www/server/data
          value: '1'
        name: vn-wwwvn-servervn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-nodeport
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  selector:
    app: ${{ defaults.app_name }}
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: ssh
    port: 22
    targetPort: 22
  - name: ftp
    port: 21
    targetPort: 21
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8888
  selector:
    app: ${{ defaults.app_name }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-redirect
  labels:
    run.claw.cloud/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: 'https://${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}/btpanel'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Exact
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8888
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      secretName: ${{ CLAWCLOUD_CERT_SECRET_NAME }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    run.claw.cloud/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8888
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      secretName: ${{ CLAWCLOUD_CERT_SECRET_NAME }}

---

apiVersion: app.claw.cloud/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://www.bt.cn/static/new/images/logo_03.svg"
  name: "btpanel"
  type: link