apiVersion: app.claw.cloud/v1
kind: Template
metadata:
  name: AllinSSL
spec:
  title: 'AllinSSL'
  type: official
  author: ClawCloud Run
  author_id: 180503656
  date: 2025-07-10
  url: 'https://www.allinssl.com/'
  gitRepo: 'https://github.com/allinssl/allinssl'
  description: 'AllinSSL is a comprehensive SSL‑certificate full‑lifecycle management tool that integrates certificate issuance, management, deployment, and monitoring'
  readme: 'https://raw.githubusercontent.com/ClawCloud/Run-Template/refs/heads/main/template/allinssl/README.md'
  icon: 'https://allinssl.com/logo.svg'
  templateType: inline
  locale: en
  categories:
    - dev-ops
    - Free-Plan-Compatible
  defaults:
    app_name:
      type: string
      value: allinssl-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:
    ACCESS_URL:
      description: "Access URL"
      type: string
      default: "allinssl"
      required: true
    ALLINSSL_USER:
      description: "user"
      type: string
      default: "allinssl"
      required: true
    ALLINSSL_PWD:
      description: "password"
      type: string
      default: "allinssldocker"
      required: true

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: docker.1ms.run/allinssl/allinssl
    deploy.run.claw.cloud/minReplicas: '1'
    deploy.run.claw.cloud/maxReplicas: '1'
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
      - name: ${{ defaults.app_name }}
        image: docker.1ms.run/allinssl/allinssl:latest
        env:
          - name: ALLINSSL_USER
            value: ${{ inputs.ALLINSSL_USER }}
          - name: ALLINSSL_PWD
            value: ${{ inputs.ALLINSSL_PWD }}
          - name: ALLINSSL_URL
            value: ${{ inputs.ACCESS_URL }}
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: data-volume
          mountPath: /www/allinssl/data
        resources:
          requests:
            cpu: 100m
            memory: 102Mi
          limits:
            cpu: 500m
            memory: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8888
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
    run.claw.cloud/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8888
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
      secretName: ${{ CLAWCLOUD_CERT_SECRET_NAME }}
---
apiVersion: app.claw.cloud/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    run.claw.cloud/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: ${{ defaults.app_host }}.${{ CLAWCLOUD_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://allinssl.com/logo.svg"
  name: "AllinSSL"
  type: link